qf: Fix qf_help: Remove attempt to grab DIM_PREFIX.
This is not available here nor will be available on
qfrc. So let's avoid duplication and just grab the qf.rst
file from whatever repository this command is called from.

Cc: Jani Nikula <jani.nikula@intel.com>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
Cc: Joonas Lahtinen <joonas.lahtinen@linux.intel.com>
Signed-off-by: Rodrigo Vivi <rodrigo.vivi@intel.com>
Acked-by: Daniel Vetter <daniel.vetter@ffwll.ch>

diff --git a/qf b/qf
--- a/qf
+++ b/qf
@@ -171,13 +171,10 @@ function quilt_clean_check
 
 function qf_help
 {
-	manpage=$DIM_PREFIX/maintainer-tools/qf.rst
+	manpage=$(dirname $(readlink -f $0))/qf.rst
 	if [ ! -e "$manpage" ]; then
-		manpage=$(dirname $(readlink -f $0))/qf.rst
-		if [ ! -e "$manpage" ]; then
-			echo "Can't find the man page."
-			exit 1
-		fi
+		echo "Can't find the man page."
+		exit 1
 	fi
 
 	if hash rst2man 2>/dev/null; then
